# NumPy - Arreglos y Matrices
**Por Álvaro Mena Monge**

Ultima actualización: 24 de febrero del 2026

NumPy es una librería de Algebra Lineal para Python, razón por la cual es tan importante para Data Science.

NumPy viene de "numerical Python"

Soporta arreglos, matrices y funciones matemáticas

# Creación de un arreglo en NumPy

In [6]:
import numpy as np #se deb importar la librería
arreglo = np.array([8, 2.3, 5, 9, 6])
print(arreglo)
arreglo

[8.  2.3 5.  9.  6. ]


array([8. , 2.3, 5. , 9. , 6. ])

In [2]:
cantidad_elementos = len(arreglo) # la función len (retorna el número de objetos) LENGTH
#len(obj=arreglo)
indices = np.arange(start=0, stop=cantidad_elementos, step=1)  # la función arange crea una secuencia de números
print(f"Índices: {indices}")
print(f"Valores: {arreglo}")

Índices: [0 1 2 3 4]
Valores: [8 9 5 9 6]


In [7]:
arreglo.dtype # muestra el tipo de datos contenidos en el arreglo

dtype('float64')

# Creación de una matriz con NumPy

In [12]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#print(matriz)

import pandas as pd
df = pd.DataFrame(matriz) # genera una data frame
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [13]:
ceros = np.zeros((3, 3)) # Crea un matriz 3x3 llena
unos = np.ones((2, 2)) # Crea una matriz 2x2 matrix llena con unos
print(ceros)
print(unos)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
